added some approval curl command

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -81,6 +81,7 @@ jobs:
           GOERLI: apps/juno-staging/overlays/staging-goerli-1/config.yaml
           INTEGRATION: apps/juno-staging/overlays/staging-integration/config.yaml
           MAINNET: apps/juno-staging/overlays/staging-mainnet/config.yaml
+          APPROVAL_STATUS: ${{ github.event.workflow_run.conclusion }}
         run: |
           curl -L \
           -X POST \
@@ -89,6 +90,21 @@ jobs:
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/NethermindEth/argo/dispatches \
           -d '{"event_type": "${{ env.EVENT_NAME }}", "client_payload":{"name": "${{ env.EVENT_NAME }}", "goerli_config": "${{ env.GOERLI }}", "integration_config": "${{ env.INTEGRATION }}", "mainnet_config": "${{ env.MAINNET }}", "tag": "${{ env.IMAGE_TAG }}"}}'
+      
+      - name: Check Approvals
+        id: check_approvals
+        run: |
+            APPROVALS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+                             -H "Accept: application/vnd.github.v3+json" \
+                             "${{ github.event.workflow_run.url }}/check-runs/${{ github.event.workflow_run.id }}/approvals" \
+                             | jq -r '.total_count')
+  
+            echo "Approvals: $APPROVALS"
+  
+            if [ "$APPROVALS" -eq 0 ]; then
+              echo "No approvals received. Cancelling workflow..."
+              exit 1  # Exit with an error code to mark the workflow as failed
+            fi
 
   deploy_to_production:
     needs: [deploy_to_staging]
